// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nxfcvllbeqomzarzvcjo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im54ZmN2bGxiZXFvbXphcnp2Y2pvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4OTg3NzgsImV4cCI6MjA2NTQ3NDc3OH0.MPHR2NuPR7_4FoGdgkmB1JxNbu9ThfzvUFK3FF_6Ad0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);